Workshop.Web/Controllers/AllowedTimeController.cs
// Controllers/AllowedTimesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using Workshop.Core.DTOs;
using Workshop.Core.DTOs.Vehicle;
using Workshop.Web.Models;
using Workshop.Web.Services;

namespace Workshop.Web.Controllers
{
    [SessionTimeout]
    public class AllowedTimeController : BaseController
    {
        private readonly WorkshopApiClient _apiClient;
        private readonly VehicleApiClient _vehicleApiClient;
        private readonly string lang;

        public AllowedTimeController(WorkshopApiClient apiClient, VehicleApiClient vehicleApiClient, 
            IConfiguration configuration, IWebHostEnvironment env, IMemoryCache cache) : base(cache, configuration, env)
        {
            _apiClient = apiClient;
            _vehicleApiClient = vehicleApiClient;
            this.lang = System.Globalization.CultureInfo.CurrentUICulture.Name;

        }

       // [CustomAuthorize(Permissions.AllowedTime.View)]
        public async Task<IActionResult> Index([FromQuery] AllowedTimeFilterDTO? filter)
        {
            filter ??= new AllowedTimeFilterDTO();
            filter.Page = filter.Page ?? 1;
            filter.PageSize = filter.PageSize ?? 25;

            var data = await _apiClient.AllowedTimeGetAllAsync(filter);

            await FillAllowedTimesProperties(data);
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("_AllowedTimesList", data);
            }

            ViewBag.Makes = await GetMakes();
            ViewBag.RTSCodes = await GetRTSCodeDTOs();

            return View(data);
        }

        //[CustomAuthorize(Permissions.AllowedTime.Edit)]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                AllowedTimeDTO? allowedTime = null;
                if (id != 0)
                {
                    allowedTime = await _apiClient.AllowedTimeGetByIdAsync(id);
                    if (allowedTime == null)
                    {
                        //return Json(new { success = false, message = "Allowed time not found" });
                        return RedirectToAction("Index");
                    }
                }

                allowedTime ??= new AllowedTimeDTO();

                //return Json(new { success = true, data = allowedTime });

                ViewBag.Makes = await GetMakes();
                ViewBag.RTSCodes = await GetRTSCodeDTOs();

                return PartialView("Edit", allowedTime);
            }
            catch (Exception ex)
            {
                //return Json(new { success = false, message = ex.Message });
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //[CustomAuthorize(Permissions.AllowedTime.Create)]
        public async Task<IActionResult> Edit(AllowedTimeDTO dto)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage);
                    return Json(new { success = false, message = "Invalid data", errors });
                }


                int result;

                if (dto.Id == 0)
                {
                    var createDto = MapToCreateDto(dto);
                    createDto.CreatedBy = UserId;
                    result = await _apiClient.AllowedTimeCreateAsync(createDto);
                }
                else
                {
                    var updateDto = MapToUpdateDto(dto);
                    updateDto.UpdatedBy = UserId;
                    var success = (await _apiClient.AllowedTimeUpdateAsync(updateDto)).IsSuccess;
                    result = success ? dto.Id : 0;
                }

                if (result > 0)
                {
                    return Json(new { success = true, message = "Allowed time saved successfully" });
                }
                else
                {
                    return Json(new { success = false, message = "Failed to save allowed time" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }

        [HttpPost]
        //[CustomAuthorize(Permissions.AllowedTime.Delete)]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var result = await _apiClient.AllowedTimeDeleteAsync(id);
                return Json(new { success = result.IsSuccess, message = result.IsSuccess ? "Allowed time deleted successfully" : "Failed to delete allowed time" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }

        private CreateAllowedTimeDTO MapToCreateDto(AllowedTimeDTO dto)
        {
            return new CreateAllowedTimeDTO
            {
                Make = dto.Make,
                Model = dto.Model,
                Year = dto.Year,
                RTSCode = dto.RTSCode,
                AllowedHours = dto.AllowedHours,
                SupervisorOverride = dto.SupervisorOverride
            };
        }

        private UpdateAllowedTimeDTO MapToUpdateDto(AllowedTimeDTO dto)
        {
            return new UpdateAllowedTimeDTO
            {
                Id = dto.Id,
                Make = dto.Make,
                Model = dto.Model,
                Year = dto.Year,
                RTSCode = dto.RTSCode,
                AllowedHours = dto.AllowedHours,
                SupervisorOverride = dto.SupervisorOverride
            };
        }


        #region Data methods
        private async Task FillAllowedTimesProperties(List<AllowedTimeListItemDTO> items)
        {
 
            if (items == null || items.Count == 0)
            {
                return;
            }

            var makes = await _vehicleApiClient.GetAllManufacturers(GetCurrentLanguage());
            var RTSCodes = await _apiClient.GetAllRTSCodesAsync(new FilterRTSCodeDTO { PageNumber = 1 });

            Dictionary<int, List<VehicleModel>> keyValuePairs = new Dictionary<int, List<VehicleModel>>();
            Func<int, Task<string>> GetMakeNameById = async (int makeId) =>
            {
                var make = makes.FirstOrDefault(m => m.Id == makeId);
                return make != null ? lang =="en"? make.ManufacturerPrimaryName :make.ManufacturerSecondaryName : "N/A";
            };

            foreach (var item in items)
            {
                item.MakeName = makes != null ? makes.Where(m => m.Id == item.Make).Select(a => lang =="en"? a.ManufacturerPrimaryName : a.ManufacturerSecondaryName).FirstOrDefault() : "N/A";
                
                if (!keyValuePairs.ContainsKey(item.Make))
                {
                    var models = await _vehicleApiClient.GetAllVehicleModel(item.Make, GetCurrentLanguage());
                    keyValuePairs[item.Make] = models;
                }

                item.ModelName = keyValuePairs[item.Make] != null ? keyValuePairs[item.Make]?.Where(m => m.ManufacturerId == item.Make).Select(a => lang == "en" ? a.VehicleModelPrimaryName : a.VehicleModelSecondaryName).FirstOrDefault()  : "N/A";
                item.RTSCode_Code = RTSCodes != null ? RTSCodes.Where(r => r.Id == item.RTSCode)?.FirstOrDefault()?.Code : "N/A";
            }
        }

        private async Task<List<SelectListItem>> GetMakes()
        {

            var makes = await _vehicleApiClient.GetAllManufacturers(GetCurrentLanguage());

            return makes.Select(m => new SelectListItem
            {
                Value = m.Id.ToString(),
                Text = lang == "en" ?  m.ManufacturerPrimaryName : m.ManufacturerSecondaryName
            }).ToList();
        }

        private async Task<List<SelectListItem>> GetRTSCodeDTOs()
        {
            var RTSCodes = await _apiClient.GetAllRTSCodesAsync(new FilterRTSCodeDTO { PageNumber = 1 });

            if (RTSCodes == null)
            {
                return new List<SelectListItem>();
            }

            return RTSCodes.Select(r => new SelectListItem
            {
                Value = r.Id.ToString(),
                Text = lang == "en"? r.PrimaryName : r.SecondaryName
            }).ToList();
        }

        private string GetCurrentLanguage()
        {
            return lang;
        }
        #endregion
    }
}

Workshop.Web/Views/AllowedTime/Edit.cshtml
@using Workshop.Core.DTOs;
@using Workshop.Resources;
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<Common> Common
@inject IStringLocalizer<Messages> Message

@model AllowedTimeDTO

@{
	var isEdit = Model.Id > 0;
	ViewBag.Title = isEdit ? Common["Edit"] : Common["Create"];
}

@using (Html.BeginForm("Edit", "AllowedTime", FormMethod.Post, new { id = "allowedTimeForm" }))
{
	@Html.AntiForgeryToken()
	@Html.HiddenFor(m => m.Id)

	<div class="modal-body">
		<div class="row">
			<div class="col-md-6 mb-3">
				@Html.LabelFor(m => m.Make, Common["Label_Make"].Value, new { @class = "form-label" })
				@Html.DropDownListFor(m => m.Make, ViewBag.Makes as List<SelectListItem>, Common["Select"].Value,
								new { @class = "form-control", required = "required", id = "MakeEditId" })
				@Html.ValidationMessageFor(m => m.Make, "", new { @class = "text-danger" })
			</div>
			<div class="col-md-6 mb-3">
			@Html.LabelFor(m => m.Model, Common["Label_Model"].Value, new { @class = "form-label" })
				@Html.DropDownListFor(m => m.Model, new List<SelectListItem>(), Common["Select"].Value,
								new { @class = "form-control", required = "required", id = "ModelEditId" })
				@Html.ValidationMessageFor(m => m.Model, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 mb-3">
			@Html.LabelFor(m => m.Year, Common["Label_Year"].Value, new { @class = "form-label" })
				@Html.EditorFor(m => m.Year, new { htmlAttributes = new { @class = "form-control", min = "1900", max = "2100", required = "required", value = Model.Year == 0 ? DateTime.Now.Year : Model.Year } })
				@Html.ValidationMessageFor(m => m.Year, "", new { @class = "text-danger" })
			</div>

		</div>

		<div class="row">
			<div class="col-md-6 mb-3">
				@Html.LabelFor(m => m.RTSCode, Common["Label_RTSCode"].Value, new { @class = "form-label" })
				@Html.DropDownListFor(m => m.RTSCode, ViewBag.RTSCodes as List<SelectListItem>, Common["SelectRTSCode"].Value,
								new { @class = "form-control", required = "required" })
				@Html.ValidationMessageFor(m => m.RTSCode, "", new { @class = "text-danger" })
			</div>
			<div class="col-md-6 mb-3">
				@Html.LabelFor(m => m.AllowedHours, Common["Label_AllowedHour"].Value, new { @class = "form-label",@maxlength="3" })
			@Html.EditorFor(m => m.AllowedHours, new { htmlAttributes = new { @class = "form-control", step = "0.001", min = "0", required = "required" , @type="number"} })
				@Html.ValidationMessageFor(m => m.AllowedHours, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="row">
			<div class="col-md-12 mb-3">
				@Html.LabelFor(m => m.SupervisorOverride, Common["Label_SupervisorOverride"].Value, new { @class = "form-label" })
				@Html.EditorFor(m => m.SupervisorOverride, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(m => m.SupervisorOverride, "", new { @class = "text-danger" })
			</div>
		</div>
	</div>
	<div class="modal-footer justify-content-center">
		<button type="submit" class="btn btn-primary"><i class="fad fa-save"></i>&nbsp;@Common["Button_Save"]</button>
	<button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fad fa-times"></i>&nbsp;@Common["Button_Cancel"]</button>
	</div>
}

<script>
	var vehicleModelId = '@Model.Model';
</script>

<script src="~/js/definitions/AllowedTime.js"></script>

Workshop.Web/Views/AllowedTime/Index.cshtml
@using Workshop.Core.DTOs;
@using Workshop.Resources;
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<Common> Common
@inject IStringLocalizer<Messages> Message

@model List<AllowedTimeListItemDTO>

@{
	ViewBag.Title = Common["AllowedTimes"];
	Layout = "~/Views/Shared/_Layout.cshtml";
	var lang = System.Globalization.CultureInfo.CurrentUICulture.Name;
}

<div class="row">
	<div class="col-12">
		<div id="panel-1" class="panel">
			<div class="panel-hdr">
				<h2 class="font-weight-bold">@Common["Label_AllowedTime"]</h2>
				<div class="panel-toolbar">
					<button type="button" class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#allowedTimeModal" onclick="resetModal()">
						<i class="fa fa-plus"></i>&nbsp;@Common["Button_AddNew"]
					</button>
				</div>
			</div>
			<div class="panel-container show">
				<div class="panel-content">

					<!-- Search Filters -->
					@* @using (Html.BeginForm("Index", "AllowedTime", FormMethod.Get, new { id = "filterForm" })) *@
					@* { *@
					<div class="row">
						<div class="col-lg-3 col-md-6 col-sm-12">
							<div class="form-group">
								@Html.Label("Make", Common["Label_Make"].Value)
								@Html.DropDownList("Make", ViewBag.Makes as List<SelectListItem>, Common["Select"].Value,
																	new { @class = "form-control", id = "Make" })
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-sm-12">
							<div class="form-group">
								@Html.Label("Model", Common["Label_Model"].Value)
								@Html.DropDownList("Model", new List<SelectListItem>(), Common["Select"].Value,
																	new { @class = "form-control", id = "Model" })
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-sm-12">
							<div class="form-group">
								@Html.Label("Year", Common["Label_Year"].Value)
								@Html.Editor("Year", new { htmlAttributes = new { id = "Year", @class = "form-control", min = "1900", max = "2100" } })
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-sm-12">
							<div class="form-group">
								@Html.Label("Engine", Common["Label_Engine"].Value)
								@Html.Editor("Engine", new { htmlAttributes = new { id = "Engine", @class = "form-control" } })
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-sm-12">
							<div class="form-group">
								<label>@Common["Label_RTSCode"]</label>
								<select asp-items="ViewBag.RTSCodes" class="form-control">
									<option value="">@Common["Select"].Value</option>
								</select>
								@Html.DropDownList("Model", ViewBag.RTSCodes , Common["Select"].Value, new { @class = "form-control", id = "Model" })
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12 text-center mt-3">
							<button type="submit" class="btn btn-primary" id="btnSearch">
								<i class="fad fa-search"></i>&nbsp;@Common["Button_Search"]
							</button>
							<button type="button" class="btn btn-secondary" onclick="resetFilter()">
								<i class="fad fa-times"></i>&nbsp;@Common["Button_Reset"]
							</button>
						</div>
					</div>

					@* } *@

					<!-- Table Container -->
					<hr />
					<div id="allowedTimeListContainer">
						@await Html.PartialAsync("_AllowedTimesList", Model)
					</div>

				</div>
			</div>
		</div>
	</div>
</div>

<!-- Allowed Time Modal -->
<div class="modal fade" id="allowedTimeModal" tabindex="-1" aria-labelledby="allowedTimeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="allowedTimeModalLabel">@Common["Label_AllowedTime"]</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body" id="allowedTimeModalBody">
				@await Html.PartialAsync("Edit", new AllowedTimeDTO())
			</div>
		</div>
	</div>
</div>

<script>
	var RazorVars = {
		editUrl: '@Url.Action("Edit", "AllowedTime")',
		indexUrl: '@Url.Action("Index", "AllowedTime")',
		deleteUrl: '@Url.Action("Delete", "AllowedTime")',
		fillVehicleModelUrl: '@Url.Action("FillVehicleModel", "VehicleDefinition")',

		// Swal texts
		msgSuccessTitle: '@Html.Raw(Common["SuccessTitle"])',
		btnOk: '@Html.Raw(Common["Ok"])',
		swalDeleteTitle: '@Message["SwalDeleteTitle"]',
		swalDeleteConfirm: '@Message["SwalDeleteConfirm"]',
		swalDeleteCancel: '@Message["SwalDeleteCancel"]',
		swalErrorHappened: '@Message["ErrorHappend"]',
		swalDeleted: '@Message["Deleted"]',
		swalCancelled: '@Message["Cancelled"]',
		year_min_message: '@Message["YearMinMessage"]',
		year_max_message: '@Message["YearMaxMessage"]',

	};

	var lang = '@lang';
</script>
<script src="~/js/definitions/AllowedTime.js"></script>

Workshop.Web/Views/AllowedTime/_AllowedTimesList.cshtml
@model List<Workshop.Core.DTOs.AllowedTimeListItemDTO>
@using Workshop.Resources;
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<Common> Common
@inject IStringLocalizer<Messages> Message

@if (Model != null && Model.Any())
{
    <table class="table table-bordered table-hover text-center w-100 main-table">
        <thead>
            <tr>
                <th>@Common["ID"]</th>
                <th>@Common["Label_Make"]</th>
                <th>@Common["Label_Model"]</th>
                <th>@Common["Label_Year"]</th>
                <th>@Common["Label_Year"]</th>
                <th>@Common["Label_RTSCode"]</th>
                <th>@Common["Label_AllowedHours"]</th>
                <th>@Common["Label_SupervisorOverride"]</th>
                <th>@Common["Label_Actions"]</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Id)</td>
                    <td>@Html.DisplayFor(modelItem => item.MakeName)</td>
                    <td>@Html.DisplayFor(modelItem => item.ModelName)</td>
                    <td>@Html.DisplayFor(modelItem => item.Year)</td>
                    <td>@Html.DisplayFor(modelItem => item.RTSCode_Code)</td>
                    <td>@Html.DisplayFor(modelItem => item.AllowedHours)</td>
                    <td>@Html.DisplayFor(modelItem => item.SupervisorOverride)</td>
                    <td>
                        <a onclick="loadAllowedTimeForEdit(@item.Id)"
                           class="btn btn-info btn-sm">
                            <i class="fad fa-pencil"></i>&nbsp;@Common["Button_Edit"]
                        </a>
                        <button class="btn btn-danger btn-sm"
                                onclick="deleteAllowedTime(@item.Id)">
                            <i class="fad fa-trash"></i>&nbsp;@Common["Delete"]
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @if (Model.First().TotalCount > 0)
    {
        <div class="d-flex justify-content-between align-items-center">
            <div>@string.Format(Common["ShowingXofYRecords"].Value, Model.Count, Model.First().TotalCount)</div>
        </div>
    }
}
<script src="~/js/site.js"></script>