Workshop.Web/Controllers/RecallController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using Newtonsoft.Json;
using NPOI.HPSF;
using NPOI.SS.UserModel;
using NPOI.SS.Util;
using NPOI.XSSF.UserModel;
using Workshop.Core.DTOs;
using Workshop.Core.DTOs.Vehicle;
using Workshop.Web.Models;
using Workshop.Web.Services;

namespace Workshop.Web.Controllers
{
    [SessionTimeout]
    public class RecallController : BaseController
    {
        private readonly WorkshopApiClient _apiClient;
        private readonly VehicleApiClient _vehicleApiClient;
        private readonly ERPApiClient _erpApiClient;
        private readonly IConfiguration _configuration;
        private readonly IWebHostEnvironment _env;
        public readonly string lang;
        public RecallController(WorkshopApiClient apiClient, ERPApiClient erpApiClient, IConfiguration configuration, 
            IWebHostEnvironment env, VehicleApiClient vehicleApiClient, IMemoryCache cache) : base(cache, configuration, env)
        {
            _apiClient = apiClient;
            _erpApiClient = erpApiClient;
            _configuration = configuration;
            _env = env;
            _vehicleApiClient = vehicleApiClient;
            this.lang = System.Globalization.CultureInfo.CurrentUICulture.Name;
        }

        [CustomAuthorize(Permissions.Recall.View)]
        public async Task<IActionResult> Index(RecallModel recall)
        {
            if (recall == null)
            {
                recall = new RecallModel();
            }
            recall.RecallFilter ??= new FilterRecallDTO();
            recall.RecallFilter.PageNumber = recall.RecallFilter.PageNumber ?? 1;
            recall.RecallFilter.Tittle = recall.RecallFilter.Tittle ?? string.Empty;
            recall.RecallFilter.Code = recall.RecallFilter.Code ?? string.Empty;

            var data = await _apiClient.GetAllRecallAsync(recall.RecallFilter);
            recall.Recalls = data ?? new List<RecallDTO>();

            return View(recall);
        }

        [CustomAuthorize(Permissions.Recall.Create)]
        public async Task<IActionResult> Edit(int Id)
        {
            var Makes = await GetMakes();
            var Vehicles = await GetVehicles();
            var Chassis = await GetChasses();
            var VehcileStatuses = await GetVehicleStatuses();
            ViewBag.Makes = Makes;
            ViewBag.Vehicles = Vehicles;
            ViewBag.ChassisNo = Chassis;
            ViewBag.VehcileStatuses = VehcileStatuses;
            if (Id > 0)
            {
                var recallItem = await _apiClient.GetRecallByIdAsync(Id);
                ViewBag.VehcilesRecall = recallItem?.Vehicles;
                return View(recallItem);
            }
            return View(new RecallDTO());
        }

        [HttpPost]
        [CustomAuthorize(Permissions.Recall.Create)]
        public async Task<IActionResult> Edit(RecallDTO recall, string recallJson)
        {
            var vehicleRecallJson = new List<VehicleRecallDTO>();
            try
            {
                vehicleRecallJson = JsonConvert.DeserializeObject<List<VehicleRecallDTO>>(recallJson);
            }catch(Exception e)
            {
            }

            ViewBag.Makes = await GetMakes();
            ViewBag.Vehicles = await GetVehicles();
            ViewBag.ChassisNo = await GetChasses();
            
            if (recall != null)
            {
                if (recall.Id > 0)
                {

                    foreach (var vehicleRecallItem in vehicleRecallJson)
                    {
                        if (recall.Vehicles == null)
                            recall.Vehicles = new List<VehicleRecallDTO>();

                        VehicleRecallDTO vehicleRecallDTO = new VehicleRecallDTO();
                        vehicleRecallDTO.Id = vehicleRecallItem.Id;
                        vehicleRecallDTO.MakeID = vehicleRecallItem.MakeID;
                        vehicleRecallDTO.ModelID = vehicleRecallItem.ModelID;
                        vehicleRecallDTO.Chassis = vehicleRecallItem.Chassis;
                        vehicleRecallDTO.RecallStatus = vehicleRecallItem.RecallStatus;
                        vehicleRecallDTO.RecallID = recall.Id;
                        if((vehicleRecallItem.Chassis == null || vehicleRecallItem.Chassis.Equals(String.Empty)) &&
                            (vehicleRecallItem.MakeID != 0 || vehicleRecallItem.MakeID != null) &&
                            (vehicleRecallItem.ModelID != 0 || vehicleRecallItem.ModelID != null))
                        {
                            //var externalVehicles = await _vehicleApiClient.GetAllExternalWSVehiclesDetails(CompanyId, vehicleRecallItem.MakeID, 
                            //    vehicleRecallItem.ModelID, null,null );
                            //foreach (var externalVehicle in externalVehicles)
                            //{
                            //    recall.Vehicles.Add(new VehicleRecallDTO { 
                            //     Chassis = externalVehicle.ChassisNo,
                            //      RecallID = recall.Id,
                            //      MakeID = vehicleRecallItem.MakeID,
                            //      ModelID = vehicleRecallItem.ModelID,
                            //        RecallStatus = vehicleRecallItem.RecallStatus
                            //    });

                            //}
                            var internalVehicles = await _vehicleApiClient.GetAllInternalWSVehiclesDetails(CompanyId, vehicleRecallItem.MakeID,
                              vehicleRecallItem.ModelID, null, null);
                            foreach (var internalVehicle in internalVehicles)
                            {
                                recall.Vehicles.Add(new VehicleRecallDTO
                                {
                                    Chassis = internalVehicle.ChassisNo,
                                    RecallID = recall.Id,
                                    MakeID = vehicleRecallItem.MakeID,
                                    ModelID = vehicleRecallItem.ModelID,
                                    RecallStatus = vehicleRecallItem.RecallStatus
                                });
 
                            }
                        }
                        else
                        recall.Vehicles.Add(vehicleRecallDTO);
                    }

                    var result = await _apiClient.UpdateRecallAsync(MapToUpdateRecall(recall));
                }
                else
                {
                    foreach (var vehicleRecallItem in vehicleRecallJson)
                    {
                        if (recall.Vehicles == null)
                            recall.Vehicles = new List<VehicleRecallDTO>();

                        VehicleRecallDTO vehicleRecallDTO = new VehicleRecallDTO();
                        vehicleRecallDTO.Id = vehicleRecallItem.Id;
                        vehicleRecallDTO.MakeID = vehicleRecallItem.MakeID;
                        vehicleRecallDTO.ModelID = vehicleRecallItem.ModelID;
                        vehicleRecallDTO.Chassis = vehicleRecallItem.Chassis;
                        vehicleRecallDTO.RecallStatus = vehicleRecallItem.RecallStatus;
                        vehicleRecallDTO.RecallID = recall.Id;
                        if ((vehicleRecallItem.Chassis == null || vehicleRecallItem.Chassis.Equals(String.Empty)) &&
                           (vehicleRecallItem.MakeID != 0 || vehicleRecallItem.MakeID != null) &&
                           (vehicleRecallItem.ModelID != 0 || vehicleRecallItem.ModelID != null))
                        {
                            //var externalVehicles = await _vehicleApiClient.GetAllExternalWSVehiclesDetails(CompanyId, vehicleRecallItem.MakeID,
                            //    vehicleRecallItem.ModelID, null, null);
                            //foreach (var externalVehicle in externalVehicles)
                            //{
                            //    recall.Vehicles.Add(new VehicleRecallDTO
                            //    {
                            //        Chassis = externalVehicle.ChassisNo,
                            //        RecallID = recall.Id,
                            //        MakeID = vehicleRecallItem.MakeID,
                            //        ModelID = vehicleRecallItem.ModelID,
                            //        RecallStatus = vehicleRecallItem.RecallStatus
                                    
                            //    });

                            //}
                            var internalVehicles = await _vehicleApiClient.GetAllInternalWSVehiclesDetails(CompanyId, vehicleRecallItem.MakeID,
                              vehicleRecallItem.ModelID, null, null);
                            foreach (var internalVehicle in internalVehicles)
                            {
                                recall.Vehicles.Add(new VehicleRecallDTO
                                {
                                    Chassis = internalVehicle.ChassisNo,
                                    RecallID = recall.Id,
                                    MakeID = vehicleRecallItem.MakeID,
                                    ModelID = vehicleRecallItem.ModelID,
                                    RecallStatus = vehicleRecallItem.RecallStatus
                                });

                            }
                        }
                        else
                            recall.Vehicles.Add(vehicleRecallDTO);
                    }
                    var result = await _apiClient.AddRecallAsync(MapToCreateRecall(recall));
                }

            }

            return RedirectToAction("Index");
        }


        [HttpPost]
        [CustomAuthorize(Permissions.Recall.Create)]
        public async Task<IActionResult> EditNoRedirect(RecallDTO recall, string recallJson)
        {

Workshop.Web/Views/Recall/Edit.cshtml
@model Workshop.Core.DTOs.RecallDTO
@using Newtonsoft.Json
@using Workshop.Resources
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<Common> Common
@inject IStringLocalizer<Messages> Message

@{
    ViewBag.Title = Common["Label_Recall"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        @using (Html.BeginForm("Edit", "Recall", FormMethod.Post, new { enctype = "multipart/form-data", id = "recallForm" }))
        {
            @Html.AntiForgeryToken()

            <div id="panel-1" class="panel">
                <div class="panel-hdr">
                    <h2 class="font-weight-bold">@Common["Label_RecallDefinition"]</h2>
                </div>

                <div class="panel-container show">
                    <div class="panel-content">
                        <div class="row" id="RecallForm">
                            <div class="row">
                                @Html.HiddenFor(model => model.Id)
                                @Html.Hidden("recallJson", new { @id = "recallJson", @name = "recallJson" })

                                <div class="col-lg-4 col-md-6 col-sm-12 my-1">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Code, @Common["Label_Code"]) <span class="text-danger">*</span>
                                        @Html.TextBoxFor(model => model.Code, new { @class = "form-control", @id = "Code" })
                                    </div>
                                </div>

                                <div class="col-lg-4 col-md-6 col-sm-12 my-1">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Title, @Common["Label_Title"]) <span class="text-danger">*</span>
                                        @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @id = "Title" })
                                    </div>
                                </div>

                                <div class="col-lg-4 col-md-6 col-sm-12 my-1">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Description, @Common["Label_Description"]) <span class="text-danger">*</span>
                                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @id = "Description", rows = "3" })
                                    </div>
                                </div>

                                <div class="col-lg-4 col-md-6 col-sm-12 my-1">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.StartDate, @Common["Label_StartDate"]) <span class="text-danger">*</span>
                                        @Html.TextBoxFor(model => model.StartDate, "{0:yyyy-MM-dd}", new { @class = "form-control flat-picker", type = "text", @id = "StartDate" })
                                    </div>
                                </div>

                                <div class="col-lg-4 col-md-6 col-sm-12 my-1">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.EndDate, @Common["Label_EndDate"]) <span class="text-danger">*</span>
                                        @Html.TextBoxFor(model => model.EndDate, "{0:yyyy-MM-dd}", new { @class = "form-control flat-picker", type = "text", @id = "EndDate" })
                                    </div>
                                </div>

                                <div class="col-lg-4 col-md-6 col-sm-12">
                                <div class="form-check form-switch mt-5">
                                @Html.CheckBoxFor(model => model.IsActive, new { @class = "form-check-input", id = "customSwitch1" })
                                @Html.LabelFor(m => m.IsActive, (string)Common["Label_IsActive"], new { @class = "form-check-label", @for = "customSwitch1" })
                                </div>

                                </div>
                            </div>

                            <div class="row mt-2">
                                @using (Html.BeginForm("ImportTemplate", "Recall", FormMethod.Post, new { enctype = "multipart/form-data", id = "excelFileForm" }))
                                {
                                    <div class="col-12">
                                        <div class="form-group">
                                            <input type="file" id="ExcelVehicle" name="ExcelVehicle" class="filepond" />
                                            <button type="button" id="RecallUpload" class="btn btn-primary btn-w-m">
                                                <i class="fa fa-save"></i>&nbsp;@Common["Label_ImportExcel"]
                                            </button>
                                        </div>
                                    </div>
                                }
                                                        <div class="col-12 mt-2">
                            <div class="position-relative">
                                <div id="gridContainer"></div>
                            </div>
                        </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="text-center text-white my-3">
                    <button type="submit" id="btnCreate" class="btn btn-primary btn-w-m">
                        <i class="fa fa-save"></i>&nbsp;@Common["Label_Save"]
                    </button>
                    <a href="@Url.Action("Index")" class="btn btn-secondary btn-w-m">
                        <i class="fa fa-arrow-left"></i>&nbsp;@Common["Label_BackToList"]
                    </a>
                </div>
            </div>
        }
    </div>
</div>

<script>
    window.LABELS = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(new {
        Id = Common["Label_ID"].Value,
        Make = Common["Label_Make"].Value,
        Model = Common["Label_Model"].Value,
        Chassis = Common["Label_Chassis"].Value,
        Action = Common["Label_Action"].Value,
        NoData = Common["Label_NoData"].Value,
        DeleteConfirmTitle = Common["Label_Confirm"].Value,
        // If you keep the message in Messages.resx, it’s fine—pull it here:
        DeleteConfirmText = Message["Message_DeleteConfirm"].Value,
        Yes = Common["Label_Yes"].Value,
        No = Common["Label_No"].Value,

        // FilePond (contains HTML; JSON keeps it intact, no &lt;...&gt;)
        FilepondIdle = Common["Label_FilepondIdle"].Value,
        FileTypeExcelOnly = Common["Validation_FileTypeExcel"].Value,
        FileRequired = Common["Validation_FileRequired"].Value
    } ));

    window.VALIDATION = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(new {
        Required   = Common["Validation_Required"].Value,
        DateRange  = Common["Validation_DateRange"].Value,
        GridRequired = Common["Validation_GridRequired"].Value,
        GridEmpty  = Common["Validation_GridEmpty"].Value
    } ));

    var MakeID        = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.Makes ?? new List<object>()));
    var Vehicle       = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.Vehicles ?? new List<object>()));
    var Chasses       = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.ChassisNo ?? new List<object>()));
    var VehcilesRecall  = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.VehcilesRecall ?? new List<object>()));
    var VehcileStatuses = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(ViewBag.VehcileStatuses ?? new List<object>()));
</script>
<script>
    window.RazorVars = Object.assign({}, window.RazorVars || {}, {
        indexUrl: '@Url.Action("Index", "Recall")',
        importTemplateUrl: '@Url.Action("ImportTemplate", "Recall")',
        downloadTemplateUrl: '@Url.Action("DownloadTemplate", "Recall")',
        deleteRecallUrl: '@Url.Action("DeleteRecall", "Recall")',
        CheckRecallCodeUniqueUrl: '@Url.Action("CheckRecallCodeUnique", "Recall")'
    });
</script>
<script src="~/js/definitions/recall.js"></script>
<script src="~/js/site.js"></script>

Workshop.Web/Views/Recall/Index.cshtml
@using Workshop.Core.DTOs
@using Workshop.Resources
@model RecallModel
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<Common> Common
@inject IStringLocalizer<Messages> Message

<div class="row">
    <div class="col-12">
        <div id="panel-1" class="panel">
            <div class="panel-hdr">
                <h2 class="font-weight-bold">@Common["Label_Recall"]</h2>
                <div class="panel-toolbar">
                    <a href="@Url.Action("Edit", "Recall")" class="btn btn-outline-primary add-record btn-sm">
                        <i class="fa fa-plus"></i>&nbsp;@Common["Label_AddNew"]
                    </a>
                </div>
            </div>
            <div class="panel-container show">
                <div class="panel-content">

                    @using (Html.BeginForm("Index", "Recall", FormMethod.Post, new { enctype = "multipart/form-data", id = "searchForm" }))
                    {
                        <div class="row">
                            <div class="col-md-6 col-sm-12">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.RecallFilter.Tittle, @Common["Label_Name"])
                                    @Html.TextBoxFor(model => model.RecallFilter.Tittle, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="col-md-6 col-sm-12">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.RecallFilter.Code, @Common["Label_Code"])
                                    @Html.TextBoxFor(model => model.RecallFilter.Code, new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="text-center mt-3 col-12">
                                <button type="submit" class="btn btn-primary" id="btnSearch">
                                    <i class="fad fa-search"></i>&nbsp;@Common["Label_Search"]
                                </button>
                                <button id="ResetBTN" type="button" class="btn btn-secondary">
                                    <i class="fad fa-times"></i>&nbsp;@Common["Label_Reset"]
                                </button>
                            </div>
                        </div>
                    }

                    <hr />
                    <div id="contentList">
                        @Html.Partial("_RecallsList", Model)
                    </div>
                    <div class="d-flex align-items-center justify-content-end">
                        <div class="mb-5 row" id="contentPager" hidden></div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<style>
    /* 1) Flip chevrons: left→right and right→left (scoped to pagination) */
    .pagination .sa.sa-chevron-left,
    .pagination .sa.sa-chevron-right {
        transform: scaleX(-1);
        display: inline-block;
    }
</style>

<script>
    window.RazorVars = Object.assign({}, window.RazorVars || {}, {
        indexUrl: '@Url.Action("Index", "Recall")',
        importTemplateUrl: '@Url.Action("ImportTemplate", "Recall")',
        downloadTemplateUrl: '@Url.Action("DownloadTemplate", "Recall")',
        deleteRecallUrl: '@Url.Action("DeleteRecall", "Recall")'
    });
</script>

<script src="~/js/definitions/recall.js"></script>

Workshop.Web/Views/Recall/_RecallsList.cshtml
@using Workshop.Core.DTOs
@using Workshop.Resources;
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<Common> Common
@inject IStringLocalizer<Messages> Message
@model RecallModel

<table id="data" class="table table-striped main-table">
    <thead>
        <tr>
            <th>@Common["Code"]</th>
            <th>@Common["ShortName"]</th>
            <th>@Common["Description"]</th>
            <th>@Common["Label_Actions"]</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Recalls){
            <tr>
                <td>
                   @item.Code
                </td>
                <td>
                    @item.Title
                </td>
                <td>
                    @item.Description
                </td>
                <td>
                    <a href="@Url.Action("Edit", "Recall", new { id = item.Id })" class="btn btn-info btn-sm add-record"><i class="fad fa-pencil"></i>&nbsp;@Common["Button_Edit"]</a>
                    <button class="btn btn-danger btn-sm DeleteBTN" data-id="@item.Id">
                        <i class="fad fa-trash"></i>&nbsp;@Common["Delete"]
                    </button>
                </td>
            </tr>
        }

    </tbody>
</table>
<script src="~/js/site.js"></script>